### ISSUE TITLE
AD DS join doesn't work with pre-staged computer accounts

### ISSUE THREAD

**Issue by SvenAelterman** [hooverken/ARMPowershell#7]
When an existing computer account is found, the computer account password should be updated to match the storage account's kerb1 key.

**Comment by hooverken** [comment]
Today's update adds support for cases where the computer object already exists in the target OU to enable cases where the customer environment requires pre-creation of computer accounts in AD.

**Comment by hooverken** [comment]
This has been fixed for a while, I'm just bad at GitHub :-)
